---
- name: install prerequisites
  apt:
    name:
       - apt-transport-https
       - ca-certificates 
       - curl 
       - gnupg-agent
       - software-properties-common
    update_cache: yes

- name: add apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: install docker 
  apt:
    name: 
       - docker-ce
       - docker-ce-cli
       - containerd.io
    update_cache: yes

- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  pip:
    name:
      - docker
      - docker-compose

- name: Starting Docker Daemon
  service:
    name: docker
    state: started
    enabled: yes

- name: deploy nginx docker container
  docker_container:
    image: nginx:stable
    name: nginx
    state: started
    auto_remove: true
    ports:
      - "8080:80"
